### ISSUE TITLE
Proposal: Integrate Pylint

### ISSUE THREAD

**Issue by mdwRepository** [the-library-code/dspace-rest-python#34]
**Description**

I propose adding Pylint as a code quality tool to this repository. Pylint is a powerful static code analysis tool for Python that helps maintain high coding standards by identifying potential errors, enforcing coding conventions, and suggesting improvements.

**Impact on the Repository**

Introducing Pylint will support the overall quality of the codebase, reduce bugs, and create a more welcoming environment for contributors by providing clear coding guidelines.

If this suggestion aligns with the goals of this project, I would be happy to help implement this feature or work on related configurations.

Looking forward to hearing your thoughts!

**Comment by kshepherd** [comment]
Fixed by #37 - would be great to include some more usage examples / info in our documentation but I can work on that before next release (or additional PRs welcome too)
