### ISSUE TITLE
get_communities method always return empty list when used with uuid

### ISSUE THREAD

**Issue by andreasgeissner** [the-library-code/dspace-rest-python#8]
Identifying a community using get_communities endpoint does not appear to be working when called directly with a uuid. The method always returns an empty list.

The reason probably is that the endpoint response does not contain an _embedded element when called directly with the uuid. See for example https://demo.dspace.org/server/api/core/communities/64b0f8cd-f323-4eea-8598-920266da756f

**Comment by kshepherd** [comment]
Thanks @andreasgeissner , I have fixed this with PR #9 

I had thought about separate get_community and get_communites methods at one stage (and so on for each DSO type) but thought a single method that allows both and always returns a list was more simple, and kept the term in line with the endpoint name. 
In implementing, I forgot to actually get for the single non-embedded result as you note!

I am interested to hear any feedback on that design decision

**Comment by kshepherd** [comment]
I have also release a new version with this fix included: https://pypi.org/project/dspace-rest-client/0.1.8/

**Comment by andreasgeissner** [comment]
Thanks @kshepherd for fixing this so quickly. 

I went the routhe to first look at which endpoints I need and then looked whether there are the respective methods in your library. So, the choice of having on method eemed prettty "natural" to me.
